import "./globals.css";

export const metadata = {
  title: "Kezia & Kris",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="">{children}</body>
    </html>
  );
}
